#!/usr/bin/env python3
"""What evidence exists that each scanner actually analysed each corpus, derived from `raw/`.

The 2026-09-01 audit counted coverage evidence for **3 of 12** scanner-by-corpus measurements and
found that Radar's 11/11, the most quoted number in this project, had no per-run log at all, while
the README admitted only the `sol-audit` gap. A findings file cannot answer the question: a
scanner that ran a case and found nothing leaves no entry, and so does a scanner that never saw
the case. That confusion is errors 20, 21 and 32.

So the matrix is derived from what is on disk, and it grades the evidence rather than reporting
a boolean:

  run log     a machine-readable log with one entry per invocation, naming every case and variant
  findings    a findings file and nothing else: proves something ran, proves nothing about coverage
  none        neither

    python tools/coverage_matrix.py            # print the matrix
    python tools/coverage_matrix.py --write    # write docs/COVERAGE.md
    python tools/coverage_matrix.py --demo
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import run_all  # noqa: E402

DOC = "docs/COVERAGE.md"


def evidence_for(raw_dir, filename):
    """(grade, detail) for one findings file."""
    path = os.path.join(raw_dir, filename)
    if not os.path.exists(path):
        return "none", "no findings file at raw/" + filename
    log = path + ".log"
    if not os.path.exists(log):
        return "findings", ("raw/" + filename + " exists; no run log, so 'found nothing' and "
                            "'never analysed' cannot be told apart")
    try:
        entries = json.load(open(log, encoding="utf-8"))
    except Exception as exc:
        return "findings", f"run log present but unreadable: {exc!r}"
    ok = sum(1 for e in entries if e.get("status") == "ok")
    bad = len(entries) - ok
    return "run log", (f"{len(entries)} invocations, {ok} ok, {bad} unavailable "
                       f"(raw/{os.path.basename(log)})")


def matrix(raw_dir="raw"):
    rows = []
    for corpus, sources in (("corpus 1", run_all.SOURCES), ("corpus 2", run_all.SOURCES_CORPUS2)):
        for scanner, (filename, _kind) in sorted(sources.items()):
            grade, detail = evidence_for(raw_dir, filename)
            rows.append({"corpus": corpus, "scanner": scanner, "file": "raw/" + filename,
                         "evidence": grade, "detail": detail})
    return rows


def render(raw_dir="raw"):
    rows = matrix(raw_dir)
    have = sum(1 for r in rows if r["evidence"] == "run log")
    out = [
        "# Coverage evidence, derived",
        "",
        "**Generated by `python tools/coverage_matrix.py --write`. Do not edit by hand;",
        "`test_all.py` recomputes it.**",
        "",
        "A findings file proves a tool ran. It does not prove which cases it ran on: a case that",
        "was analysed and came back empty looks exactly like a case that was never opened. This",
        "project has published both mistakes, in both directions, and they are errors 20, 21 and",
        "32 in the engineering log. So every row below says which kind of evidence exists, and the",
        "weak kinds are named rather than rounded up.",
        "",
        f"**{have} of {len(rows)} measurements have a per-run log.**",
        "",
        "| corpus | scanner | evidence | detail |",
        "|---|---|---|---|",
    ]
    for r in rows:
        mark = {"run log": "**run log**", "findings": "findings only", "none": "**none**"}[
            r["evidence"]]
        out.append(f"| {r['corpus']} | `{r['scanner']}` | {mark} | {r['detail']} |")
    out += [
        "",
        "## What is still missing, said plainly",
        "",
    ]
    weak = [r for r in rows if r["evidence"] != "run log"]
    if weak:
        for r in weak:
            out.append(f"- **{r['scanner']}, {r['corpus']}**: {r['detail']}")
    else:
        out.append("- nothing: every measurement in the clock has a per-run log.")
    out += [
        "",
        "A row with `findings only` is not a wrong number. It is a number whose denominator",
        "rests on the absence of entries in a file, which is the shape of error 20 and is exactly",
        "how `solsec` came to be published as `0 / 6, 3 unavailable` when a per-case run later",
        "showed 34 invocations, 34 successes and zero unavailable.",
        "",
    ]
    return "\n".join(out)


def demo():
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        assert evidence_for(d, "nope.json")[0] == "none"
        with open(os.path.join(d, "a.json"), "w") as fh:
            fh.write("[]")
        assert evidence_for(d, "a.json")[0] == "findings"
        with open(os.path.join(d, "a.json.log"), "w") as fh:
            json.dump([{"leaf": "x/insecure", "status": "ok"},
                       {"leaf": "x/secure", "status": "unavailable"}], fh)
        grade, detail = evidence_for(d, "a.json")
        assert grade == "run log", grade
        assert "2 invocations, 1 ok, 1 unavailable" in detail, detail
    assert "| corpus | scanner | evidence | detail |" in render()
    print("coverage_matrix: OK")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--demo", action="store_true")
    args = ap.parse_args()
    if args.demo:
        demo()
        return 0
    text = render()
    print(text)
    if args.write:
        with open(DOC, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("\nwritten: " + DOC)
    return 0


if __name__ == "__main__":
    sys.exit(main())
